## credit : chatGPT https://chat.openai.com/
# continuous integration
name: pocgdx-ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the prod branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # gradlew_bin setup provided by gradle/gradle-build-action@v2
  gradlew_bin: /home/runner/gradle-installations/installs/gradle-7.5/bin/gradle

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.5

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and package Desktop application
      run: chmod +x ${gradlew_bin} && ${gradlew_bin} desktop:dist

    - name: Build and package Android application
      run: ${gradlew_bin} android:assembleRelease

    - name: Build and package HTML application
      run: ${gradlew_bin} html:dist

#    - name: Build and package iOS application - DISABLED seems to need  MobiVM &nd xcode project (.xcodeproj file)
#      run: |
#        # Install dependencies for iOS build
#        sudo gem install cocoapods
#        cd ios
#        pod install
#
#        # Build iOS application
#        ${gradlew_bin} ios:packIOSApp

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Application Artifacts
        path: |
          desktop/build/libs/*.jar
          android/build/outputs/apk/release/*.apk
          html/build/dist/*
          ios/build/robovm/*.ipa