## credit : chatGPT https://chat.openai.com/
# continuous integration
name: pocgdx-ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the prod branch
  push:
    # Sequence of patterns matched against refs/heads
    branches: [ main ]
    # Sequence of patterns matched against refs/tags
    tags:
      - v*
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # gradlew_bin setup provided by gradle/gradle-build-action@v2
  gradlew_bin: /home/runner/gradle-installations/installs/gradle-7.5/bin/gradle

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.5

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and package Desktop application
      run: chmod +x ${gradlew_bin} && ${gradlew_bin} desktop:dist

    - name: Build and package Android application
      run: ${gradlew_bin} android:assembleRelease

    - name: Build and package HTML application
      run: |
        ${gradlew_bin} html:dist
        tar -czvf html/build/html.tgz -C html/build/dist/ .

#    - name: Build and package iOS application - DISABLED seems to need  MobiVM &nd xcode project (.xcodeproj file)
#      run: |
#        # Install dependencies for iOS build
#        sudo gem install cocoapods
#        cd ios
#        pod install
#
#        # Build iOS application
#        ${gradlew_bin} ios:packIOSApp

# create artifacts for the next job
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: |
          LICENSE
          desktop/build/libs/*.jar
          android/build/outputs/apk/release/*.apk
          html/build/dist/*
#          ios/build/robovm/*.ipa

  publish-release:
    needs: build
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
    permissions: write-all
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-output
        path: ./

    - name: Produce release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Build packages"
        files: |
          LICENSE
          desktop/build/libs/*.jar
          html/build/html.tgz
          android/build/outputs/apk/release/*.apk
